"""add a todo.complete

Revision ID: 7e6dea9e2762
Revises: a6b9c8c8da15
Create Date: 2017-01-01 23:09:56.802751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6dea9e2762'
down_revision = 'a6b9c8c8da15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('finished', sa.Text(), nullable=True))
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.TEXT(), nullable=True))
    op.drop_column('todos', 'finished')
    # ### end Alembic commands ###
