"""add a todo.complete

Revision ID: a6b9c8c8da15
Revises: f999955b105d
Create Date: 2017-01-01 21:13:37.254349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b9c8c8da15'
down_revision = 'f999955b105d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
